### ISSUE TITLE
Unclear how to set the privacy budget

### ISSUE THREAD

**Issue by Miguel-Fuentes** [dkifer/ResidualPlanner#1]
I have been looking through the ResidualPlanner class and I'm not sure how to run it with a specific (epsilon, delta) privacy budget. Can you explain how to set the budget (either in terms of approximate DP or zCDP)?

**Comment by JackyXiao98** [comment]
Thanks for the comment, the code is updated. 

To use ResidualPlanner with a specific privacy budget rho, we can use the following code. 

sum_var = system.selection(choice="sumvar", pcost=2*rho)

To use (epsilon, delta)-DP, we can first convert it to rho-zCDP and use the code above.
